//AST(rettype, parent, name, vars)

AST(Value, Expr, Assign, const Token* name; UniquePtr<Expr> value;,return )
AST(Value, Expr, Binary, UniquePtr<Expr> left; const Token* op; UniquePtr<Expr> right;,return )
AST(Value, Expr, Call, UniquePtr<Expr> callee; const Token* paren; Array<UniquePtr<Expr>> args;,return )
AST(Value, Expr, Grouping, UniquePtr<Expr> expr;,return )
AST(Value, Expr, Literal, Value value;,return )
AST(Value, Expr, Logical, UniquePtr<Expr> left; const Token* op; UniquePtr<Expr> right;,return )
AST(Value, Expr, Unary, const Token* op; UniquePtr<Expr> right;,return )
AST(Value, Expr, Variable, const Token* name;,return )

AST(void, Stmt, Block, Array<UniquePtr<Stmt>> stmts;,)
AST(void, Stmt, Expression, UniquePtr<Expr> expr;,)
AST(void, Stmt, Function, const Token* name; Array<const Token*> params; Array<UniquePtr<Stmt>> body;,)
AST(void, Stmt, If, UniquePtr<Expr> condition; UniquePtr<Stmt> thenBranch; UniquePtr<Stmt> elseBranch;,)
AST(void, Stmt, Print, UniquePtr<Expr> expr;,)
AST(void, Stmt, Return, const Token* keyword; UniquePtr<Expr> value;,)
AST(void, Stmt, Var, const Token* name; UniquePtr<Expr> initializer;,)
AST(void, Stmt, While, UniquePtr<Expr> condition; UniquePtr<Stmt> body;,)
